notify_package:
    notify:
      - platform: telegram
        name: telegram_dxdy
        chat_id: !secret telegram_bot_dxdy_chat_id

      - platform: telegram
        name: telegram_oav
        chat_id: !secret telegram_bot_oav_chat_id

      - platform: group
        name: telegram_family
        services:
          - service: telegram_dxdy
          - service: telegram_oav
      
      - platform: group
        name: mobile_app_family
        services:
          - service: mobile_app_dxdy
          - service: mobile_app_oav
      
      - platform: smtp
        name: smtp_dxdy
        sender: !secret admin_email
        recipient: !secret admin_email
        server: smtp.mail.ru
        port: 465
        encryption: tls
        timeout: 15
        username: !secret admin_email
        password: !secret email_admin_password

