notify_package:
    notify:
      - platform: telegram
        name: telegram_dxdy
        chat_id: !secret telegram_bot_dxdy_chat_id

      - platform: telegram
        name: telegram_oav
        chat_id: !secret telegram_bot_oav_chat_id

      - platform: group
        name: telegram_family
        services:
          - service: telegram_dxdy
          - service: telegram_oav
      
      - platform: group
        name: mobile_app_family
        services:
          - service: mobile_app_dxdy
          - service: mobile_app_oav