person_package:
    group:
      family:
        entities:
          - person.dxdy
          - person.aleksandra

    homeassistant:
      customize:
        person.dxdy:
          entity_picture: https://avatars2.githubusercontent.com/u/2061165?s=88&v=4
        person.aleksandra:
          entity_picture: https://sun9-68.userapi.com/c850236/v850236988/271ee/iRzpFmY1DI8.jpg?ava=1
