speech_package:
    yandex_station_intents:
      intents:
        Включи свет на кухне:
        Выключи свет на кухне:
        Включи свет в гостиной:
        Выключи свет в гостиной:
        Включи свет над цветами:
          extra_phrases:
            - Включи свет над цветами в гостиной
        Выключи свет над цветами:
          extra_phrases:
            - Выключи свет над цветами в гостиной
        Включи свет в душевой:
        Выключи свет в душевой:
        Включи свет в спальне:
        Выключи свет в спальне:
        Включи свет в детской:
        Выключи свет в детской:
