speech_package:
  yandex_station_intents:
    intents:
      # Свет
      Включи гирлянду в гостиной:
        extra_phrases:
          - Включи гирлянду
      Выключи гирлянду в гостиной:
        extra_phrases:
          - Выключи гирлянду
      Включи ёлку:
        extra_phrases:
          - Ёлочка гори
      Выключи ёлку:
      Выключи свет в доме:
        extra_phrases:
          - Выключи свет в квартире
      # Уборка
      Пропылесось на кухне:
        extra_phrases:
          - Пропылесось кухню
      Пропылесось в гостиной:
        extra_phrases:
          - Пропылесось гостиную
      Пропылесось в спальне:
        extra_phrases:
          - Пропылесось спальню
      Пропылесось в детской:
        extra_phrases:
          - Пропылесось детскую
      Пропылесось в душевой:
        extra_phrases:
          - Пропылесось душевую
      Пропылесось в ванной:
        extra_phrases:
          - Пропылесось ванную
      Пропылесось плитку в коридоре:
        extra_phrases:
          - Пропылесось плитку
      Пропылесось в коридоре:
        extra_phrases:
          - Пропылесось коридор
      Пропылесось в доме:
        extra_phrases:
          - Пропылесось
          - Включи пылесось
      Отправь пылесос на базу:
        extra_phrases:
          - Отправь пылесос домой

      # Остальное
      Я ушел:
        extra_phrases:
          - Я ушла
        say_phrase: Поняла, я начинаю уборку
      Мы уехали:
        extra_phrases:
          - Я уехал
          - Я уехала
        say_phrase: Поняла, поставила дом на сигнализацию
      Доброе утро:
        say_phrase: Спасибо! Хорошего дня 
  automation:
    - alias: Сказать Алисе, что я ушел
      trigger:
          - platform: event
            event_type: yandex_intent
            event_data:
              text: Я ушел
      action:
          - service: vacuum.start
            entity_id: vacuum.pylesos_maksimka

          - service: switch.turn_off
            entity_id: switch.vykliuchateli_v_dome

          - service: light.turn_off
            entity_id: light.svet_v_dome

          - service: media_player.turn_off
            entity_id: media_player.media_pleery
      
    - alias: Сказать Алисе, что мы уехали
      trigger:
        - platform: event
          event_type: yandex_intent
          event_data:
            text: Мы уехали
      action:
        - service: input_boolean.turn_on
          entity_id: input_boolean.alarm_system
    
    - alias: Сказать Алисе доброе утро
      trigger:
        - platform: event
          event_type: yandex_intent
          event_data:
            text: Доброе утро
      action:
        - service: switch.turn_on
          entity_id: switch.0x00124b0024c1ecb5

        - service: input_datetime.set_datetime
          target:
            entity_id: input_datetime.hallway_light_starts_at
          data:
            time: "{{ now().strftime('%H:%M:%S') }}"

        - service: input_datetime.set_datetime
          target:
            entity_id: input_datetime.shower_night_light_ends_at
          data:
            time: "{{ now().strftime('%H:%M:%S') }}"