windows_package:
  input_datetime:
    working_alarm_time:
      name: Подъем на работу
      icon: mdi:timer
      has_date: false
      has_time: true
    weekend_alarm_time:
      name: Подъем в выходной
      icon: mdi:timer
      has_date: false
      has_time: true

  automation:
    - alias: Закрыть шторы в спальне
      trigger:
          platform: time
          at: "20:30:00"
      condition:
        condition: state
        entity_id: input_boolean.alarm_system
        state: 'off'
      action:
        service: cover.close_cover
        entity_id: cover.0x00124b0029ded4a3

    - alias: Открыть шторы в спальне в рабочий день
      trigger:
        platform: time
        at: input_datetime.working_alarm_time
      condition:
        - condition: state
          entity_id: binary_sensor.rabochii_den
          state: 'on'
        - condition: state
          entity_id: input_boolean.alarm_system
          state: 'off'
      action:
        - delay: '00:03:00'
        - service: cover.open_cover
          entity_id: cover.0x00124b0029ded4a3

    - alias: Открыть шторы в спальне в выходной день
      trigger:
        platform: time
        at: input_datetime.weekend_alarm_time
      condition:
        - condition: state
          entity_id: binary_sensor.rabochii_den
          state: 'off'
        - condition: state
          entity_id: input_boolean.alarm_system
          state: 'off'
      action:
        - delay: '00:03:00'
        - service: cover.open_cover
          entity_id: cover.0x00124b0029ded4a3
