windows_package:
  input_datetime:
    working_alarm_time:
      name: Подъем на работу
      icon: mdi:timer
      has_date: false
      has_time: true
    weekend_alarm_time:
      name: Подъем в выходной
      icon: mdi:timer
      has_date: false
      has_time: true
