
# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:

automation:
config:

frontend:
  themes: !include_dir_merge_named themes

mobile_app:
person:
script:
ssdp:
sun:
system_health:
zeroconf:
python_script:
webhook:
energy:

recorder:
   db_url: "postgresql://postgres:postgres@0.0.0.0/homeassistant"
   include:
     entities:
       - sensor.0x00158d00044afc42_temperature
       - sensor.0x00158d00039e4a23_temperature
       - sensor.0x00158d000418d85c_temperature
       - sensor.ble_temperature_a4c138fb313d
       - sensor.ble_temperature_a4c1389cc8c3
       - sensor.ble_temperature_a4c138f88a98
       - sensor.0x00158d000418d85c_humidity
       - sensor.0x00158d00039e4a23_humidity
       - sensor.0x00158d00044afc42_humidity
       - sensor.ble_humidity_a4c138fb313d
       - sensor.ble_humidity_a4c1389cc8c3
       - sensor.ble_humidity_a4c138f88a98
       - binary_sensor.0x00158d0005443bfb_contact
       - sensor.0x00124b00234c8afc_co2
       - sensor.0x00124b00234c8801_co2
       - sensor.0x00124b001ec85723_co2
       - switch.0x00124b00272a7348_state_l4
       - switch.0x00124b00272a7348_state_l3
       - switch.0x00124b00272a7348_state_l2
       - climate.lytko_5130000
       - sensor.gas
       - sensor.power
       - sensor.bath_hot_water
       - sensor.bath_cold_water
       - sensor.shower_hot_water
       - sensor.shower_cold_water
       - sensor.power_cost
       - sensor.gas_price
       - sensor.gas_cost
       - sensor.hot_water_price
       - sensor.bath_hot_water_cost
       - sensor.cold_water_price
       - sensor.bath_cold_water_cost
       - sensor.bath_hot_water
       - sensor.shower_hot_water_cost
       - sensor.cold_water_price
       - sensor.shower_cold_water_cost
       - input_boolean.alarm_system
       - input_datetime.working_alarm_time
       - input_datetime.weekend_alarm_time
       - select.0x00124b00180597b4_mode
       - switch.0x00124b00180597b4_sound
       - climate.thermostat

history:

homeassistant:
  packages: !include_dir_merge_named packages/
  external_url: !secret homeassistant_url
  currency: RUB
  country: RU 

mqtt:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
