
# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:

automation:
config:

frontend:
  themes: !include_dir_merge_named themes

mobile_app:
person:
script:
ssdp:
sun:
system_health:
updater:
zeroconf:
python_script:
webhook:

recorder:
   include:
     entities:
       - sensor.0x00158d00044afc42_temperature
       - sensor.0x00158d00039e4a23_temperature
       - sensor.0x00158d000418d85c_temperature
       - sensor.dushevaia_temperature
       - sensor.0x00158d000418d85c_humidity
       - sensor.0x00158d00039e4a23_humidity
       - sensor.0x00158d00044afc42_humidity
       - sensor.dushevaia_humidity

history:
   include:
     entities:
       - sensor.0x00158d00044afc42_temperature
       - sensor.0x00158d00039e4a23_temperature
       - sensor.0x00158d000418d85c_temperature
       - sensor.dushevaia_temperature
       - sensor.0x00158d000418d85c_humidity
       - sensor.0x00158d00039e4a23_humidity
       - sensor.0x00158d00044afc42_humidity
       - sensor.dushevaia_humidity

homeassistant:
  packages: !include_dir_named packages

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_access_token 

http:
  base_url: !secret homeassistant_url

mqtt:
  discovery: true
  broker: 'localhost'
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
