version: '3'

services:
  mpd:
    container_name: mpd
    build:
      context: ./mpd/docker
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - ./mpd/mpd.conf:/mpd/conf/mpd.conf
      - ./mpd/music:/mpd/music
      - ./mpd/playlists:/mpd/playlists
      - ./mpd/data:/mpd/data
    devices:
      - /dev/snd:/dev/snd
  duckdns:
    container_name: duckdns
    image: linuxserver/duckdns:latest
    restart: always
    network_mode: host
    env_file:
      - ./duckdns/.env
  nginx_certbot:
    container_name: nginx_certbot
    image: mrdxdy/nginx-certbot:0.1.0
    restart: always
    network_mode: host
    volumes:
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:0.107.4
    restart: always
    volumes:
      - ./homeassistant/config:/config
    network_mode: host
    environment:
      - TZ=Europe/Moscow
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:1.6.8
    network_mode: host
    restart: always
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.10.0
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    privileged: true
    network_mode: host
    environment:
      - TZ=Europe/Moscow
