version: '3'

services:
  duckdns:
    container_name: duckdns
    image: linuxserver/duckdns:latest
    restart: always
    network_mode: host
    env_file:
      - ./duckdns/.env
  nginx_certbot:
    container_name: nginx_certbot
    image: mrdxdy/nginx-certbot:0.1.0
    restart: always
    network_mode: host
    volumes:
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./homeassistant/config:/homeassistant
  homeassistant:
    container_name: homeassistant
    image: homeassistant/raspberrypi4-homeassistant:2021.4.6
    restart: always
    privileged: true
    volumes:
      - ./homeassistant/config:/config
    network_mode: host
    environment:
      - TZ=Europe/Moscow
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:1.6.8
    network_mode: host
    restart: always
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/conf.d:/mosquitto/conf.d
      - ./mqtt/ssl:/mosquitto/ssl
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.18.1
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    privileged: true
    network_mode: host
    environment:
      - TZ=Europe/Moscow
