version: '3'

services:
  disk:
    image: mrdxdy/nginx-file-browser:0.1.0
    restart: always
    ports:
      - 8081:80
    volumes:
      - /buffer/samba:/opt/www/files
    networks:
      my-smart-home:
  syncthing:
    image: syncthing/syncthing:1.23
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - STGUIADDRESS=127.0.0.1:8384
    volumes:
      - ./syncthing:/var/syncthing
    network_mode: host
    restart: always
  postgresql:
    image: postgres:alpine3.17
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=homeassistant
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_INITDB_ARGS="-E utf8"
    volumes:
      - ./postgresql/pgdata:/var/lib/postgresql/data
  torrserver:
    image: yourok/torrserver
    restart: always
    network_mode: host
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./torrserver/db:/TS/db
  nginx_certbot:
    container_name: nginx_certbot
    image: mrdxdy/nginx-certbot:0.1.2
    restart: always
    network_mode: host
    volumes:
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./homeassistant/config:/homeassistant
      - ./nginx/auth:/etc/nginx/auth
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:2023.11.3
    restart: always
    privileged: true
    depends_on:
      - postgresql
    volumes:
      - ./homeassistant/config:/config
    network_mode: host
    environment:
      - TZ=Europe/Moscow
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:1.6.8
    network_mode: host
    restart: always
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/conf.d:/mosquitto/conf.d
      - ./mqtt/ssl:/mosquitto/ssl
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.33.2
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
    privileged: true
    network_mode: host
    environment:
      - TZ=Europe/Moscow
  esphome:
    container_name: esphome
    image: esphome/esphome:2023.12.5
    volumes:
      - ./esphome/config:/config
    restart: always
    privileged: true
    network_mode: host
    environment:
      - TZ=Europe/Moscow

networks:
  my-smart-home:
