bedroom_light_package:
  yeelight:
    devices:
      192.168.1.6:
        name: Свет в спальне
        save_on_change: true

  script:
    set_comfortable_light:
      sequence:
        - service: light.turn_on
          data_template:
            entity_id: light.svet_v_spalne
            kelvin: > 
              {% if states.sun.sun.state == "above_horizon" %} 
                {{ 6500 }} 
              {% else  %} 
                {{ 2000 }} 
              {% endif %}
            brightness: >
              {% if states.sun.sun.state == "above_horizon" %}
                {{ 255 }}
              {% else %}
                {{ 1 }}
              {% endif %}

  light:
    - platform: template
      lights:
        bedroom_light:
          value_template: "{{ state('light.svet_v_spalne') }}"
          turn_on:
            service: script.set_comfortable_light
          turn_off:
            service: light.turn_off
            entity_id: light.svet_v_spalne
  automation:
    - alias: 'Если свет в спальне включили через FLEX выключатель'
      mode: single
      trigger:
        - platform: state
          entity_id: light.svet_v_spalne
          to: 'on'
      condition:
        - condition: template
          value_template: '{{ trigger.to_state.context.user_id is none }}'
        - condition: template
          value_template: '{{ trigger.to_state.context.parent_id is none }}'
      action:
        - service: script.set_comfortable_light

    - alias: 'Включить ночник'
      mode: queued
      max: 5
      trigger:
        - platform: state
          entity_id: 
            - sensor.0x00158d000424fa2c_click
            - sensor.0x00158d000424fadf_click
          to: 'single'
      action:
        - service: yeelight.set_mode
          data:
            entity_id: light.svet_v_spalne
            mode: moonlight

    - alias: 'Включить свет в спальне'
      mode: queued
      max: 5
      trigger:
        - platform: state
          entity_id:
            - sensor.0x00158d000424fa2c_click
            - sensor.0x00158d000424fadf_click
          to: 'double'
      action:
        - service: script.set_comfortable_light

    - alias: 'Выключить свет в спальне'
      mode: queued
      max: 5
      trigger:
        - platform: state
          entity_id:
            - sensor.0x00158d000424fa2c_click
            - sensor.0x00158d000424fadf_click
          to: 'long'
      action:
        - service: light.turn_off
          entity_id: light.svet_v_spalne