bedroom_light_package:
  automation:
    - alias: 'Включить ночник'
      mode: queued
      max: 5
      trigger:
        - platform: state
          entity_id: 
            - event.0x00158d000424fa2c_action
            - event.0x00158d000424fadf_action
          to: ~
      conditions:
          - condition: template
            value_template: "{{trigger.from_state.state != 'unavailable'}}"
          - condition: template
            value_template: "{{trigger.to_state.attributes.event_type == 'single'}}"
      action:
        - service: switch.turn_on
          data:
            entity_id: switch.0xa4c138a8528e6d04_right

    - alias: 'Включить свет в спальне'
      mode: queued
      max: 5
      trigger:
        - platform: state
          entity_id:
            - event.0x00158d000424fa2c_action
            - event.0x00158d000424fadf_action
          to: ~
      conditions:
          - condition: template
            value_template: "{{trigger.from_state.state != 'unavailable'}}"
          - condition: template
            value_template: "{{trigger.to_state.attributes.event_type == 'double'}}"
      action:
        - service: switch.turn_on
          data:
            entity_id: switch.0xa4c138a8528e6d04_left

    - alias: 'Выключить свет в спальне'
      mode: queued
      max: 5
      trigger:
        - platform: state
          entity_id:
            - event.0x00158d000424fa2c_action
            - event.0x00158d000424fadf_action
          to: ~
      conditions:
          - condition: template
            value_template: "{{trigger.from_state.state != 'unavailable'}}"
          - condition: template
            value_template: "{{trigger.to_state.attributes.event_type == 'hold'}}"
      action:
        - service: switch.turn_off
          entity_id:
            - switch.0xa4c138a8528e6d04_left
            - switch.0xa4c138a8528e6d04_right 