hallway_light_package:
    switch:
      - platform: group
        name: "Выключатели в прихожей"
        entities:
          - switch.0xa4c13845d5d8c9a3_left
          - switch.0xa4c1380aed5b5a4a
          
    automation:
      - alias: 'Включить свет в большой прихожей через датчик движения'
        trigger:
          - platform: state
            entity_id: binary_sensor.0x00158d00041faacf_occupancy
            to: 'on'
        condition:
          - condition: time
            after: '08:00:00'
            before: '21:00:00'
        action:
          - service: switch.turn_on
            entity_id: switch.0xa4c13845d5d8c9a3_left

      - alias: 'Выключить свет в большой прихожей через датчик движения'
        trigger:
          - platform: state
            entity_id: binary_sensor.0x00158d00041faacf_occupancy
            to: 'off'
        action:
          - service: switch.turn_off
            entity_id: switch.0xa4c13845d5d8c9a3_left

      - alias: Включить свет в прихожей через алису
        trigger:
            - platform: event
              event_type: yandex_intent
              event_data:
                text: Включи свет в прихожей
        action:
            - service: switch.turn_on
              entity_id: switch.0xa4c1380aed5b5a4a
      - alias: Выключить свет в прихожей через алису
        trigger:
            - platform: event
              event_type: yandex_intent
              event_data:
                text: Выключи свет в прихожей
        action:
            - service: switch.turn_off
              entity_id: switch.0xa4c1380aed5b5a4a