hallway_light_package:
  template:
      # Idea 1: https://www.youtube.com/watch?v=SK9CYq5GtH8
      # Idea 2: https://www.youtube.com/watch?v=B0N0D82Ozkc
    - binary_sensor:
        - name: 0xa4c13845d5d8c9a3_left_light
          state: >
            {{ is_state('binary_sensor.0x00158d00041faacf_occupancy', 'off')
                and is_state('switch.0xa4c13845d5d8c9a3_left', 'on') 
            }}
          delay_on: 00:01:00
  switch:
    - platform: group
      name: "Выключатели в прихожей"
      entities:
        - switch.0xa4c13845d5d8c9a3_left
        - switch.0xa4c1380aed5b5a4a

  input_datetime:
    hallway_light_starts_at:
      has_date: false
      has_time: true
      initial: '07:00'
    hallway_light_ends_at:
      has_date: false
      has_time: true
      initial: '21:00'

  automation:
    - alias: Сброс времени включения света в прихожей
      trigger:
        platform: time
        at: '23:59:59'
      action:
        - service: input_datetime.set_datetime
          target:
            entity_id: input_datetime.hallway_light_starts_at
          data:
            time: "07:00:00"

    - alias: 'Включить/выключить свет в большой прихожей через датчик движения'
      trigger:
        - platform: state
          entity_id: binary_sensor.0x00158d00041faacf_occupancy
        - platform: state
          entity_id: binary_sensor.0xa4c13845d5d8c9a3_left_light
      action:
        - choose:
          - conditions:
              - condition: state
                entity_id: binary_sensor.0x00158d00041faacf_occupancy
                state: 'on'
              - condition: state
                entity_id: switch.0xa4c13845d5d8c9a3_left
                state: 'off'
              - condition: time
                after: input_datetime.hallway_light_starts_at
                before: input_datetime.hallway_light_ends_at
            sequence:
              - service: switch.turn_on
                entity_id: switch.0xa4c13845d5d8c9a3_left
          - conditions:
              - condition: state
                entity_id: binary_sensor.0xa4c13845d5d8c9a3_left_light
                state: 'on'
            sequence:
                - service: switch.turn_off
                  entity_id: switch.0xa4c13845d5d8c9a3_left
