house_light_package:
  switch:
    - platform: group
      name: "Выключатели в доме"
      entities:
        - switch.0xa4c1381fc1e36875_left
        - switch.0xa4c1381fc1e36875_right
        - switch.0xa4c13845d5d8c9a3_right
        - switch.0xa4c1380aed5b5a4a
        - switch.0xa4c13845d5d8c9a3_left
        - switch.0xa4c138fad011d9df
  light:
    - platform: group
      name: "Свет в доме"
      entities:
        - light.svet_v_spalne