shower_light_package:
  automation:
    - alias: Включить свет в душевой через алису
      trigger:
        - platform: event
          event_type: yandex_intent
          event_data:
            text: Включи свет в душевой
      action:
        - service: switch.turn_on
          entity_id: switch.0xa4c13845d5d8c9a3_right

    - alias: Выключить свет в душевой через алису
      trigger:
        - platform: event
          event_type: yandex_intent
          event_data:
            text: Выключи свет в душевой
      action:
        - service: switch.turn_off
          entity_id: switch.0xa4c13845d5d8c9a3_right