hallway_cleaning_package:
  automation:
    - alias: Попросить Алису пропылесосить в прихожей
      trigger:
          - platform: event
            event_type: yandex_intent
            event_data:
              text: Пропылесось в коридоре
      action:
          - service: xiaomi_miio.vacuum_clean_segment
            data:
              segments:
                - 17
                - 19
            target:
              entity_id: vacuum.pylesos_maksimka

    - alias: Попросить Алису пропылесосить плитку в прихожей
      trigger:
          - platform: event
            event_type: yandex_intent
            event_data:
              text: Пропылесось плитку в коридоре
      action:
          - service: xiaomi_miio.vacuum_clean_segment
            data:
              segments:
                - 17
            target:
              entity_id: vacuum.pylesos_maksimka