# Issue https://github.com/rytilahti/python-miio/issues/1272
# miiocli roborockvacuum --ip <ip> --token <token> segment_clean [7]
# room ids:
# 1 - детская
# 4 - ванная
# 7 - спальня
# 8 - душевая
# 16 - кухня
# 17 - плитка в прихожей
# 18 - гостиная
# 19 - ламинат в прихожей
house_cleaning_package:
  automation:
    - alias: Попросить Алису пропылесосить в квартире
      trigger:
          - platform: event
            event_type: yandex_intent
            event_data:
              text: Пропылесось в доме
      action:
          - service: xiaomi_miio.vacuum_clean_segment
            data:
              segments:
                - 1
                - 4
                - 7
                - 8
                - 16
                - 17
                - 18
                - 19
            target:
              entity_id: vacuum.pylesos_maksimka

    - alias: Попросить Алису отправить пылесос на базу
      trigger:
          - platform: event
            event_type: yandex_intent
            event_data:
              text: Отправь пылесос на базу
      action:
          - service: vacuum.return_to_base
            entity_id: vacuum.pylesos_maksimka