vacuum:
  - platform: xiaomi_miio
    host: !secret vacuum_host
    token: !secret vacuum_token
    name: Пылесос Максимка

    #smartthinq:
    #  token: !secret smartthinq_token
    #  region: RU
    #  language: ru-RU

automation:
  - alias: Стиральная машинка закончила стирку
    trigger:
      - platform: state
        entity_id: device_tracker.washer
        to: 'not_home'
        from: 'home'
    action:
      - service: notify.telegram_family
        data:
          title: ''
          message: Стиральная машинка закончила стирку
