sensor:
  - platform: mqtt
    name: "rpi_co2"
    state_topic: "/rpi/co2"
    unit_of_measurement: "ppm"

  - platform: mitemp_bt
    whitelist:
      - '58:2D:34:36:AB:19'
    encryptors:
      'A4:C1:38:FB:31:3D': '75b58807305a3254ea925a841b978a70'
    hci_interface: !secret ha_bluetooth_id 

weather:
  - platform: gismeteo
    name: weather
    mode: daily

automation:
  - alias: Проветрить спальню перед сном
    trigger:
    - at: '22:20:00'
      platform: time
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{ state_attr('sensor.0x00158d000418d85c_temperature', 'temperature') - state_attr('weather.weather', 'temperature') >= 5 }}"
        - condition: template
          value_template: "{{ state_attr('sensor.0x00158d000418d85c_temperature', 'temperature') > 21 }}"
    action:
      - service: media_player.volume_set
        entity_id: media_player.yandex_station_ff98f02970565b8d4d33fe93
        data_template:
          volume_level: 0.5

      - service: media_player.play_media
        entity_id: media_player.yandex_station_ff98f02970565b8d4d33fe93
        data:
          media_content_id: "В спальне {{ state_attr('sensor.0x00158d000418d85c_temperature', 'temperature') | round(0) | int }} градусов. Рекомендую проветрить комнату перед сном."
          media_content_type: text
