# для интеграции с Алисой
lock:
  - platform: template
    name: domofon_door
    unique_id: domofon_door
    value_template: "{{ states('select.0x00124b00180597b4_mode') == 'never' or states('select.0x00124b00180597b4_mode') == 'drop' }}"
    lock:
      - service: select.select_option
        data:
          entity_id: select.0x00124b00180597b4_mode
          option: 'never'
    unlock:
      - service: select.select_option
        data:
          entity_id: select.0x00124b00180597b4_mode
          option: 'once'

script:
  accept_domofon:
    sequence:
      - service: select.select_option
        data:
          entity_id: select.0x00124b00180597b4_mode
          option: 'once'
      - delay:
          seconds: 3
      - service: select.select_option
        data:
          entity_id: select.0x00124b00180597b4_mode
          option: 'never'
  reject_domofon:
    sequence:
      - service: select.select_option
        data:
          entity_id: select.0x00124b00180597b4_mode
          option: 'drop'
      - delay:
          seconds: 3
      - service: select.select_option
        data:
          entity_id: select.0x00124b00180597b4_mode
          option: 'never'


# Idea from https://github.com/Anonym-tsk/smart-domofon/blob/master/ge1mer/homeassistant/domofon.yaml
automation:
  - alias: Domofon incoming call notification
    initial_state: true
    trigger:
      # Обнаружен звонок
      - platform: state
        entity_id: sensor.0x00124b00180597b4_state
        to: 'ring'
    action:
      - choose:
          # Включён режим авто-открыть или авто-открыть-один-раз
          - conditions:
              - condition: or
                conditions:
                  - condition: state
                    entity_id: select.0x00124b00180597b4_mode
                    state: 'once'
                  - condition: state
                    entity_id: select.0x00124b00180597b4_mode
                    state: 'always'
            sequence:
              # Отправить уведомление
              - service: notify.telegram_family
                data:
                  message: "Звонок в домофон (откроется автоматически)"
          # Включён режим авто-отклонить
          - conditions:
              - condition: state
                entity_id: select.0x00124b00180597b4_mode
                state: 'drop'
            sequence:
              # Отправить уведомление
              - service: notify.telegram_family
                data:
                  message: "Звонок в домофон (отклонится автоматически)"
        default:
          # Отправить уведомление с кнопками Открыть/Отклонить
          - service: notify.telegram_family
            data:
              message: "Звонок в домофон"
              data:
                inline_keyboard:
                  - "{{ 'Открыть:/domofon_open, Отклонить:/domofon_reject' }}"

  - alias: Telegram /domofon_open callback
    initial_state: true
    trigger:
      # Из телеграмма пришла команда Открыть
      - platform: event
        event_type: telegram_callback
        event_data:
          data: '/domofon_open'
    action:
      - choose:
          # Идет звонок
          - conditions:
              - condition: state
                entity_id: sensor.0x00124b00180597b4_state
                state: 'ring'
            sequence:
              # Отправить подтверждение о намерении открыть
              - service: notify.telegram_family
                data:
                  message: "Открываю..."
              # Открыть
              - service: script.accept_domofon
        default:
          # Отправить ответ, что нету звонка
          - service: notify.telegram_family
            data:
              message: "Нет входящего звонка"

  - alias: Telegram /domofon_reject callback
    initial_state: true
    trigger:
      # Из телеграмма пришла команда Отклонить
      - platform: event
        event_type: telegram_callback
        event_data:
          data: '/domofon_reject'
    action:
      - choose:
          # Идет звонок
          - conditions:
              - condition: state
                entity_id: sensor.0x00124b00180597b4_state
                state: 'ring'
            sequence:
              # Отправить подтверждение о намерении отклонить
              - service: notify.telegram_family
                data:
                  message: "Отклоняю..."
              # Отклонить
              - service: script.reject_domofon
        default:
          # Отправить ответ, что нету звонка
          - service: notify.telegram_family
            data:
              message: "Нет входящего звонка"

  - alias: 'Выключить звук домофона в обеденный сон'
    trigger:
      - platform: time
        at: '12:30'
    action:
      - service: switch.turn_off
        entity_id: switch.0x00124b00180597b4_sound

  - alias: 'Включить звук домофона после обеденного сона'
    trigger:
      - platform: time
        at: '16:30'
    action:
      - service: switch.turn_on
        entity_id: switch.0x00124b00180597b4_sound

  - alias: 'Выключить звук домофона на ночь'
    trigger:
      - platform: time
        at: '21:00'
    action:
      - service: switch.turn_off
        entity_id: switch.0x00124b00180597b4_sound

  - alias: 'Утром включить звук домофона'
    trigger:
      - platform: time
        at: '09:00'
    action:
      - service: switch.turn_on 
        entity_id: switch.0x00124b00180597b4_sound
