#switch:
#  - platform: xiaomi_miio
#    name: Цветы в детской
#    host: !secret xiaomi_socket_host_1
#    token: !secret xiaomi_socket_token_1
#    model: chuangmi.plug.hmi206

automation:
  - id: '1575133776894'
    alias: Включить свет у цветов
    description: ''
    trigger:
    - at: 07:00:00
      platform: time
    condition: []
    action:
    - alias: ''
      data:
        entity_id: switch.0x000d6f0013369f96
      service: switch.turn_on
    - alias: ''
      data:
        entity_id: light.0x00158d00025d5546
      service: light.turn_on
  - id: '1575133850822'
    alias: Выключить свет у цветов
    description: ''
    trigger:
    - at: '22:00:00'
      platform: time
    condition: []
    action:
    - alias: ''
      data:
        entity_id: switch.0x000d6f0013369f96
      service: switch.turn_off
    - alias: ''
      data:
        entity_id: light.0x00158d00025d5546
      service: light.turn_off
