yeelight:
  devices:
    192.168.1.6:
      name: Свет в спальне

script:
  turn_on_comfortable_light:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: light.svet_v_spalne
          kelvin: > 
           {% if states.sun.sun.state == "above_horizon" %} 
             {{ 6500 }} 
           {% else  %} 
             {{ 2000 }} 
           {% endif %}
          brightness: >
           {% if states.sun.sun.state == "above_horizon" %}
             {{ 255 }}
           {% else %}
             {{ 1 }}
           {% endif %}
           
automation:
  - alias: 'Включить ночник'
    mode: queued
    max: 5
    trigger:
      - platform: state
        entity_id: 
          - sensor.0x00158d000424fa2c_click
          - sensor.0x00158d000424fadf_click
        to: 'single'
    action:
      - service: light.turn_on
        entity_id: light.svet_v_spalne_nightlight

  - alias: 'Включить свет в спальне'
    mode: queued
    max: 5
    trigger:
      - platform: state
        entity_id:
          - sensor.0x00158d000424fa2c_click
          - sensor.0x00158d000424fadf_click
        to: 'double'
    action:
      - service: script.turn_on_comfortable_light

  - alias: 'Выключить свет в спальне'
    mode: queued
    max: 5
    trigger:
      - platform: state
        entity_id:
          - sensor.0x00158d000424fa2c_click
          - sensor.0x00158d000424fadf_click
        to: 'long'
    action:
      - service: light.turn_off
        entity_id:
          - light.svet_v_spalne_nightlight
          - light.svet_v_spalne

  - alias: 'Включить свет в большой прихожей через датчик движения'
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d00041faacf_occupancy
        to: 'on'
    condition:
      - condition: time
        after: '08:00:00'
        before: '21:00:00'
    action:
      - service: switch.turn_on
        entity_id: switch.0xa4c13845d5d8c9a3_left

  - alias: 'Выключить свет в большой прихожей через датчик движения'
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d00041faacf_occupancy
        to: 'off'
    action:
      - service: switch.turn_off
        entity_id: switch.0xa4c13845d5d8c9a3_left
