group:
  all_lights:
    - light.svet_v_spalne
    - light.sonoff_1000a8d068_1
    - light.sonoff_1000a8d068_2

binary_sensor:
  - platform: template
    sensors:
      hall_switch:
        friendly_name: "Выключатель в прихожей"
        value_template: "{{ is_state('binary_sensor.0x00158d0004280ab6_contact', 'on') }}"
      bed_switch:
        friendly_name: "Выключатель в спальне"
        value_template: "{{ is_state('binary_sensor.0x00158d00044d5691_contact', 'on') }}"

yeelight:
  devices:
    192.168.1.6:
      name: Свет в спальне

script:
  turn_on_moonlight:
    sequence:
      - service: yeelight.set_mode
        data:
          entity_id: light.svet_v_spalne
          mode: moonlight
      - service: light.turn_on
        data:
          entity_id: light.svet_v_spalne
          brightness: 1
  start_sunrise:
    sequence:
      - service: script.turn_on_moonlight
      - delay: 00:03:00
      - service: light.turn_on
        data:
          entity_id: light.svet_v_spalne
          brightness_pct: 25
      - delay: 00:03:00
      - service: light.turn_on
        data:
          entity_id: light.svet_v_spalne
          brightness_pct: 50
      - delay: 00:03:00
      - service: light.turn_on
        data:
          entity_id: light.svet_v_spalne
          brightness_pct: 75
      - delay: 00:03:00
      - service: light.turn_on
        data:
          entity_id: light.svet_v_spalne
          brightness_pct: 100
      #- delay: 00:03:00
      #- service: light.turn_on
      #  data:
      #    entity_id: light.svet_v_spalne
      #    kelvin: 3000
      #    brightness_pct: 1

automation:
  - alias: 'Включить ночник'
    mode: queued
    max: 5
    trigger:
      - platform: state
        entity_id: 
          - sensor.0x00158d000424fa2c_click
          - sensor.0x00158d000424fadf_click
        to: 'single'
    action:
      - service: script.turn_on_moonlight

  - alias: 'Включить или выключить свет в спальне через выключатель'
    mode: queued
    max: 5
    trigger:
      - platform: state
        entity_id: binary_sensor.bed_switch
    action:
      - service: light.toggle
        data:
          entity_id: light.svet_v_spalne
          color_temp: 1
          brightness: 255

  - alias: 'Включить свет в спальне'
    mode: queued
    max: 5
    trigger:
      - platform: state
        entity_id:
          - sensor.0x00158d000424fa2c_click
          - sensor.0x00158d000424fadf_click
        to: 'double'
    action:
      - service: light.turn_on
        data:
          entity_id: light.svet_v_spalne
          color_temp: 1
          brightness: 255

  - alias: 'Выключить свет в спальне'
    mode: queued
    max: 5
    trigger:
      - platform: state
        entity_id:
          - sensor.0x00158d000424fa2c_click
          - sensor.0x00158d000424fadf_click
        to: 'long'
    action:
      - service: light.turn_off
        entity_id: light.svet_v_spalne

  - alias: 'Включить свет в большой прихожей через датчик движения'
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d00041faacf_occupancy
        to: 'on'
    action:
      - service: light.turn_on
        entity_id: light.sonoff_1000a8d068_2

  - alias: 'Включить свет в прихожей через выключатель'
    trigger:
      - platform: state
        entity_id: binary_sensor.hall_switch
        to: 'on'
    action:
      - service: light.turn_on
        entity_id: light.sonoff_1000a8d068_1
      - service: light.turn_on
        entity_id: light.sonoff_1000a8d068_2

  - alias: 'Только вечером включать свет в прихожей у ванной через датчик движения'
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d000421cf9a_occupancy
        to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: light.turn_on
        entity_id: light.sonoff_1000a8d068_1

  - alias: 'Выключить свет в прихожей через выключатель'
    trigger:
      - platform: state
        entity_id: binary_sensor.hall_switch
        to: 'off'
    action:
      - service: light.turn_off
        entity_id: light.sonoff_1000a8d068_1
      - service: light.turn_off
        entity_id: light.sonoff_1000a8d068_2

  - alias: 'Выключить свет в большой прихожей через датчик движения'
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d00041faacf_occupancy
        to: 'off'
    condition:
      - condition: state
        entity_id: binary_sensor.hall_switch
        state: 'off'
    action:
      - service: light.turn_off
        entity_id: light.sonoff_1000a8d068_2

  - alias: 'Выключить свет в прихожей у ванной через датчик движения'
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d000421cf9a_occupancy
        to: 'off'
    condition:
      - condition: state
        entity_id: binary_sensor.hall_switch
        state: 'off'
    action:
      - service: light.turn_off
        entity_id: light.sonoff_1000a8d068_1
