
group:
  all_lights:
    - light.svet_v_spalne
    - light.sonoff_1000a8d068_1
    - light.sonoff_1000a8d068_2
    - switch.0x00124b0024c1ecb5
    - switch.0x00124b0024c34eca
    - switch.0x00124b0024c3375f
    - switch.0x00124b0024c33795
  kitchen_lights:
    - switch.0x00124b0024c34eca
  lounge_lights:
    - switch.0x00124b0024c1ecb5
    - switch.0x00124b0024c3375f
    - switch.0x00124b0024c33795

binary_sensor:
  - platform: template
    sensors:
      hall_switch:
        friendly_name: "Выключатель в прихожей"
        value_template: "{{ is_state('binary_sensor.0x00158d0004280ab6_contact', 'on') }}"
      bed_switch:
        friendly_name: "Выключатель в спальне"
        value_template: "{{ is_state('binary_sensor.0x00158d00044d5691_contact', 'on') }}"
      lounge_switch:
        friendly_name: "Выключатель в гостиной"
        value_template: "{{ is_state('binary_sensor.0x00158d00076a5f2d_contact', 'on') }}"
      kitchen_switch:
        friendly_name: "Выключатель на кухне"
        value_template: "{{ is_state('binary_sensor.0x00158d00076a9ef6_contact', 'on') }}"

yeelight:
  devices:
    192.168.1.6:
      name: Свет в спальне

script:
  turn_on_comfortable_light:
    sequence:
      - service: light.turn_on
        data_template:
          entity_id: light.svet_v_spalne
          kelvin: > 
           {% if states.sun.sun.state == "above_horizon" %} 
             {{ 6500 }} 
           {% else  %} 
             {{ 2000 }} 
           {% endif %}
          brightness: >
           {% if states.sun.sun.state == "above_horizon" %}
             {{ 255 }}
           {% else %}
             {{ 1 }}
           {% endif %}

  turn_off_comfortable_light:
    sequence:
      - service: light.turn_off
        entity_id: light.svet_v_spalne

  toogle_comfortable_light:
    sequence:
      - service_template: > 
         {% if is_state('light.svet_v_spalne', 'off') %} 
           script.turn_on_comfortable_light 
         {% else %} 
           script.turn_off_comfortable_light 
         {% endif %}

  toggle_lounge_light:
    sequence:
      - service_template: >
         {% if is_state('switch.0x00124b0024c3375f', 'on') or is_state('switch.0x00124b0024c33795', 'on') or is_state('switch.0x00124b0024c1ecb5', 'on') %}
           homeassistant.turn_off
         {% else %}
           homeassistant.turn_on
         {% endif %}
        entity_id: group.lounge_lights
           
  turn_on_moonlight:
    sequence:
      - service: yeelight.set_mode
        data:
          entity_id: light.svet_v_spalne
          mode: moonlight
      - service: light.turn_on
        data:
          entity_id: light.svet_v_spalne
          brightness: 1
  start_sunrise:
    sequence:
      - service: script.turn_on_moonlight
      - delay: 00:03:00
      - service: light.turn_on
        data:
          entity_id: light.svet_v_spalne
          brightness_pct: 25
      - delay: 00:03:00
      - service: light.turn_on
        data:
          entity_id: light.svet_v_spalne
          brightness_pct: 50
      - delay: 00:03:00
      - service: light.turn_on
        data:
          entity_id: light.svet_v_spalne
          brightness_pct: 75
      - delay: 00:03:00
      - service: light.turn_on
        data:
          entity_id: light.svet_v_spalne
          brightness_pct: 100
      #- delay: 00:03:00
      #- service: light.turn_on
      #  data:
      #    entity_id: light.svet_v_spalne
      #    kelvin: 3000
      #    brightness_pct: 1

automation:
  - alias: 'Включить ночник'
    mode: queued
    max: 5
    trigger:
      - platform: state
        entity_id: 
          - sensor.0x00158d000424fa2c_click
          - sensor.0x00158d000424fadf_click
        to: 'single'
    action:
      - service: script.turn_on_moonlight

  - alias: 'Включить или выключить свет в спальне через выключатель'
    mode: queued
    max: 5
    trigger:
      - platform: state
        entity_id: binary_sensor.bed_switch
    action:
      - service: script.toogle_comfortable_light

  - alias: 'Включить свет в спальне'
    mode: queued
    max: 5
    trigger:
      - platform: state
        entity_id:
          - sensor.0x00158d000424fa2c_click
          - sensor.0x00158d000424fadf_click
        to: 'double'
    action:
      - service: script.turn_on_comfortable_light

  - alias: 'Выключить свет в спальне'
    mode: queued
    max: 5
    trigger:
      - platform: state
        entity_id:
          - sensor.0x00158d000424fa2c_click
          - sensor.0x00158d000424fadf_click
        to: 'long'
    action:
      - service: script.turn_off_comfortable_light

  - alias: 'Включить свет в большой прихожей через датчик движения'
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d00041faacf_occupancy
        to: 'on'
    condition:
      - condition: time
        after: '07:00:00'
        before: '22:00:00'
    action:
      - service: light.turn_on
        entity_id: light.sonoff_1000a8d068_2

  - alias: 'Включить свет в прихожей через выключатель'
    trigger:
      - platform: state
        entity_id: binary_sensor.hall_switch
        to: 'on'
    action:
      - service: light.turn_on
        entity_id: light.sonoff_1000a8d068_1
      - service: light.turn_on
        entity_id: light.sonoff_1000a8d068_2

  - alias: 'Только вечером включать свет в прихожей у ванной через датчик движения'
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d000421cf9a_occupancy
        to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: light.turn_on
        entity_id: light.sonoff_1000a8d068_1

  - alias: 'Выключить свет в прихожей через выключатель'
    trigger:
      - platform: state
        entity_id: binary_sensor.hall_switch
        to: 'off'
    action:
      - service: light.turn_off
        entity_id: light.sonoff_1000a8d068_1
      - service: light.turn_off
        entity_id: light.sonoff_1000a8d068_2

  - alias: 'Выключить свет в большой прихожей через датчик движения'
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d00041faacf_occupancy
        to: 'off'
    condition:
      - condition: state
        entity_id: binary_sensor.hall_switch
        state: 'off'
    action:
      - service: light.turn_off
        entity_id: light.sonoff_1000a8d068_2

  - alias: 'Выключить свет в прихожей у ванной через датчик движения'
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d000421cf9a_occupancy
        to: 'off'
    condition:
      - condition: state
        entity_id: binary_sensor.hall_switch
        state: 'off'
    action:
      - service: light.turn_off
        entity_id: light.sonoff_1000a8d068_1
  - alias: 'Включить или выключить свет в гостиной'
    trigger:
      - platform: state
        entity_id: binary_sensor.lounge_switch
    action:
      - service: script.toggle_lounge_light
  - alias: 'Включить или выключить свет через выключатель на кухне'
    trigger:
      - platform: state
        entity_id: binary_sensor.kitchen_switch
    action:
      - service: homeassistant.toggle
        entity_id: group.kitchen_lights
