binary_sensor:
  - platform: template
    sensors:
      hall_switch:
        friendly_name: Выключатель
        value_template: "{{ is_state('binary_sensor.0x00158d0004280ab6_contact', 'on') }}"

automation:
  - alias: 'Включить свет в большой прихожей через датчик движения'
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d00041faacf_occupancy
        to: 'on'
    action:
      - service: light.turn_on
        entity_id: light.sonoff_1000a8d068_2

  - alias: 'Включить свет в прихожей через выключатель'
    trigger:
      - platform: state
        entity_id: binary_sensor.hall_switch
        to: 'on'
    action:
      - service: light.turn_on
        entity_id: light.sonoff_1000a8d068_1
      - service: light.turn_on
        entity_id: light.sonoff_1000a8d068_2

  - alias: 'Только вечером включать свет в прихожей у ванной через датчик движения'
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d000421cf9a_occupancy
        to: 'on'
    condition:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
    action:
      - service: light.turn_on
        entity_id: light.sonoff_1000a8d068_1

  - alias: 'Выключить свет в прихожей через выключатель'
    trigger:
      - platform: state
        entity_id: binary_sensor.hall_switch
        to: 'off'
    action:
      - service: light.turn_off
        entity_id: light.sonoff_1000a8d068_1
      - service: light.turn_off
        entity_id: light.sonoff_1000a8d068_2

  - alias: 'Выключить свет в большой прихожей через датчик движения'
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d00041faacf_occupancy
        to: 'off'
    condition:
      - condition: state
        entity_id: binary_sensor.hall_switch
        state: 'off'
    action:
      - service: light.turn_off
        entity_id: light.sonoff_1000a8d068_2

  - alias: 'Выключить свет в прихожей у ванной через датчик движения'
    trigger:
      - platform: state
        entity_id: binary_sensor.0x00158d000421cf9a_occupancy
        to: 'off'
    condition:
      - condition: state
        entity_id: binary_sensor.hall_switch
        state: 'off'
    action:
      - service: light.turn_off
        entity_id: light.sonoff_1000a8d068_1
