switch:
  - platform: template
    switches:
      hisense_tv:
        icon_template: >
          {% if is_state('switch.hisense_tv', 'on') %}
            {{ 'mdi:television-classic' }}
          {% else %}
            {{ 'mdi:television-classic-off' }}
          {% endif %}
        friendly_name: 'Hisense TV'
        value_template: >
          {{ is_state('device_tracker.hisense_tv', 'home') }}
        turn_on:
          service: wake_on_lan.send_magic_packet
          data:
            mac: !secret hisensetv_mac
        turn_off:
          service: mqtt.publish
          data:
            topic: !secret turn_off_hisensetv_topic
            payload: 'KEY_POWER'

device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.1.3
    home_interval: 1

wake_on_lan:

media_player:
  - platform: samsungtv_custom
    host: !secret samsungtv_host
    port: 8001
    name: Телевизор в гостиной
    mac: !secret samsungtv_mac
 
  - platform: mpd
    host: 127.0.0.1
    name: Колонки на кухне

# Samsung tv is evil
automation:
  - alias: 'Turn off kitchen speakers if samsung tv in living room turns on'
    trigger:
      - platform: state
        entity_id: media_player.televizor_v_gostinoi
        from: 'off'
        to: 'on'
    action:
      - service: media_player.turn_off
        entity_id: media_player.kolonki_na_kukhne
