yandex_station:
  username: !secret yandex_username
  password: !secret yandex_password

yandex_smart_home:

# Samsung tv is evil
automation:
  - alias: 'Turn off kitchen speakers if samsung tv in living room turns on'
    trigger:
      - platform: state
        entity_id: device_tracker.samsung
        from: 'not_home'
        to: 'home'
    action:
      - service: media_player.turn_off
        entity_id: media_player.yandex_station_lb0000000000000717140000f8d0c603
