media_player:
  - platform: samsungtv_custom
    host: !secret samsungtv_host
    port: 8001
    name: Телевизор в гостиной
    mac: !secret samsungtv_mac
 
  - platform: mpd
    host: 127.0.0.1
    name: Колонки на кухне

# Samsung tv is evil
automation:
  - alias: 'Turn off kitchen speakers if samsung tv in living room turns on'
    initial_state: 'off'
    trigger:
      - platform: state
        entity_id: media_player.televizor_v_gostinoi
        from: 'off'
        to: 'on'
    action:
      - service: media_player.turn_off
        entity_id: media_player.kolonki_na_kukhne
