panel_iframe:
  z2m:
    title: Z2M
    url: !secret z2m_url
    icon: mdi:chemical-weapon
    require_admin: true
  torr:
    title: Torrent
    url: !secret torr_url
    icon: mdi:filmstrip
    require_admin: true
