shopping_list:

script:
  update_shopping_list:
    alias: Update yandex shopping list
    sequence:
      - variables:
          station: media_player.yandex_station_lb0000000000000717140000f8d0c603 
      - service: media_player.volume_mute
        data:
          entity_id: "{{ station }}"
          is_volume_muted: true
      - service: media_player.play_media
        data:
          entity_id: "{{ station }}"
          media_content_id: update
          media_content_type: shopping_list
      - delay:
          milliseconds: 300
      - service: media_player.play_media
        data:
          entity_id: "{{ station }}"
          media_content_id: "стоп"
          media_content_type: command
      - service: media_player.volume_mute
        data:
          entity_id: "{{ station }}"
          is_volume_muted: false

automation:
  - alias: "Sync with yandex shopping list"
    trigger:
      - platform: event
        event_type: shopping_list_updated
    action:
      - service: script.update_shopping_list
