input_boolean:
  alarm_system:
    name: Сигнализация
    initial: off

automation:
  - alias: Кто-то проник в дом
    trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d0005443bfb_contact
      to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.alarm_system
        state: 'on'
    action:
    - data:
        message: Кто-то проник в дом
      service: notify.telegram_family

  - alias: Протечка на кухне
    trigger: 
    - platform: state
      entity_id: binary_sensor.0x00158d00049fc6ec_water_leak
      to: 'on'
    action:
    - data:
        message: На кухне протечка
      service: notify.telegram_family

  - id: '1576001180625'
    alias: Протечка в ванной
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d000400f5c7_water_leak
      to: 'on'
    condition: []
    action:
    - data:
        message: В ванной протечка
      service: notify.telegram_family

  - alias: Протечка в душевой
    description: ''
    trigger:
    - platform: state
      entity_id: binary_sensor.0x00158d0004235519_water_leak
      to: 'on'
    condition: []
    action:
    - data:
        message: В душевой комнате протечка
      service: notify.telegram_family

  - alias: Нужно снять показания со счетчиков и отдать в УК
    description: ''
    trigger:
    - at: '20:00:00'
      platform: time
    condition:
      condition: template
      value_template: '{{ now().day == 19 }}'
    action:
    - alias: ''
      data:
        title: ''
        message: Нужно снять показания со счетчиков и завтра отдать в УК
      service: notify.telegram_family

  - alias: Завтра последний день чтобы отдать в УК показания счетчиков
    description: ''
    trigger:
    - at: '20:00:00'
      platform: time
    condition:
      condition: template
      value_template: '{{ now().day == 21 }}'
    action:
    - alias: ''
      data:
        title: ''
        message: Завтра последний день чтобы отдать в УК показания счетчиков
      service: notify.telegram_family
