zigbee2mqtt_networkmap:

panel_iframe:
  zigbee_map:
    title: 'Zigbee map'
    url: '/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'

automation:
  alias: 'Zigbee Map update'
  hide_entity: true
  trigger:
    platform: time_pattern
    minutes: '/10'
    seconds: 00
  action:
    service: zigbee2mqtt_networkmap.update
